spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todos
    username: todos-user
    password: asd
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: todowebapp

logging:
  level:
    org.springframework: info
    com.jinho.springboot.todowebapp: debug
